"""Phase 1.7 — Auto-write PHASE1_DECISION.md from gate JSONs."""
from __future__ import annotations

import json
from pathlib import Path

import _runner_utils as ru

PHASE = "phase1.7"
PHASE_DIR = ru.GDTR_ROOT / "results" / PHASE
LOG = ru.setup_logging(PHASE)


def safe_load(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception as e:
        LOG.warning("could not load %s: %s", p, e)
        return {}


def main() -> None:
    with ru.phase_context(PHASE, PHASE_DIR):
        gate_a_un = safe_load(ru.GDTR_ROOT / "results" / "phase1.1" / "gate_a_evo_untuned.json")
        gate_a_tu = safe_load(ru.GDTR_ROOT / "results" / "phase1.3" / "gate_a_tuned.json")
        cal = safe_load(ru.GDTR_ROOT / "results" / "phase1.4" / "calibration.json")
        hp = safe_load(ru.GDTR_ROOT / "results" / "phase1.5" / "best_hp.json")
        gate_b = safe_load(ru.GDTR_ROOT / "results" / "phase1.6" / "gate_b.json")

        md = []
        md.append("# PHASE 1 DECISION (auto-generated)\n")
        md.append("Generated by `scripts/17_phase1_7_writeup.py` from per-phase gate JSONs.\n")

        md.append("## Phase 1.1 Gate A_evo (untuned)\n")
        md.append("```json")
        md.append(json.dumps(gate_a_un.get("verdict_untuned", {}), indent=2))
        md.append("```")
        md.append(f"- M2_jsd overall: {gate_a_un.get('M2_jsd_overall', 'NA')}  (CI={gate_a_un.get('M2_jsd_ci95', 'NA')})")
        md.append(f"- M2_cos overall: {gate_a_un.get('M2_cos_overall', 'NA')}")
        md.append(f"- per-block-type M2_jsd: {gate_a_un.get('per_block_M2_jsd', 'NA')}")

        md.append("\n## Phase 1.3 Gate A_evo (tuned)\n")
        md.append("```json")
        md.append(json.dumps(gate_a_tu.get("verdict", {}), indent=2))
        md.append("```")
        md.append(f"- per-block tuned M2_jsd: {gate_a_tu.get('per_block_M2_jsd_tuned', 'NA')}")

        md.append("\n## Phase 1.4 Calibration (q70 of D_cos at penultimate layer)\n")
        md.append("```json")
        md.append(json.dumps(cal, indent=2))
        md.append("```")

        md.append("\n## Phase 1.5 HP sweep (sanity proxy)\n")
        md.append("```json")
        md.append(json.dumps(hp, indent=2))
        md.append("```")

        md.append("\n## Phase 1.6 Gate B_evo (chr22 exon vs intron)\n")
        md.append("```json")
        md.append(json.dumps(gate_b.get("verdict_gate_b", {}), indent=2))
        md.append("```")
        md.append(f"- per-context: {gate_b.get('per_context', 'NA')}")

        md.append("\n## Overall Phase 1 verdict\n")
        ok_a = gate_a_un.get("verdict_untuned", {}).get("overall_pass", False) or gate_a_tu.get("verdict", {}).get("overall_pass", False)
        ok_b = gate_b.get("verdict_gate_b", {}).get("overall_pass", False)
        md.append(f"- Gate A_evo: **{'PASS' if ok_a else 'FAIL'}**")
        md.append(f"- Gate B_evo: **{'PASS' if ok_b else 'FAIL'}**")
        md.append(f"- Overall: **{'PASS' if (ok_a and ok_b) else 'FAIL'}**")

        out_path = ru.GDTR_ROOT / "PHASE1_DECISION.md"
        out_path.write_text("\n".join(md))
        LOG.info("wrote %s", out_path)
        ru.write_done(PHASE, PHASE_DIR, {"out": str(out_path)})


if __name__ == "__main__":
    main()
