"""Phase 2.6 — Auto-write PHASE2_DECISION.md aggregating all sub-stage outputs."""
from __future__ import annotations

import json
from pathlib import Path

import _runner_utils as ru
ru.add_repo_paths()

PHASE = "phase2.6"
PHASE_OUT_DIR = ru.GDTR_ROOT / "results" / "phase2.6"
LOG = ru.setup_logging(PHASE)


def safe_load(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception as e:
        LOG.warning("could not load %s: %s", p, e)
        return {}


def main() -> None:
    with ru.phase_context(PHASE, PHASE_OUT_DIR, step_name="writeup"):
        gate_b = safe_load(ru.GDTR_ROOT / "results" / "phase2.2" / "gate_b_chr17.json")
        cross = safe_load(ru.GDTR_ROOT / "results" / "phase2.3" / "cross_chr_comparison.json")
        gene_class = safe_load(ru.GDTR_ROOT / "results" / "phase2.4" / "gene_class_stratification.json")
        splice = safe_load(ru.GDTR_ROOT / "results" / "phase2.5" / "splice_chr17_profile.json")
        prep_done = safe_load(ru.GDTR_ROOT / "results" / "phase2.0" / "_prep_chr17_done")
        fwd_done = safe_load(ru.GDTR_ROOT / "results" / "phase2.1" / "_chr17_forward_done")

        md = []
        md.append("# PHASE 2 DECISION (auto-generated)\n")
        md.append("Generated by `scripts/26_phase2_6_writeup.py` from sub-stage gate JSONs.\n")
        md.append(f"γ_cos = 0.39663 (Phase 1.4 locked). cosine_lens uses `final_key='norm'` (Bug 1 fix).\n")

        md.append("\n## Phase 2.0 — chr17 prep\n")
        md.append("```json")
        md.append(json.dumps(prep_done, indent=2))
        md.append("```")

        md.append("\n## Phase 2.1 — chr17 forward\n")
        md.append("```json")
        md.append(json.dumps(fwd_done, indent=2))
        md.append("```")

        md.append("\n## Phase 2.2 — Gate B chr17 (exon vs intron)\n")
        md.append("```json")
        md.append(json.dumps(gate_b.get("verdict_gate_b", {}), indent=2))
        md.append("```")
        md.append(f"- per-context counts: {gate_b.get('context_counts', 'NA')}")
        md.append(f"- per-context mean c: { {k: v.get('mean_c') for k, v in gate_b.get('per_context', {}).items()} }")

        md.append("\n## Phase 2.3 — Cross-chromosome (chr17 vs chr22)\n")
        md.append("```json")
        md.append(json.dumps(cross.get("replication_verdict", {}), indent=2))
        md.append("```")
        md.append("Per-context comparison (chr17_mean_c | chr22_mean_c | delta | KS p):")
        md.append("")
        md.append("| context | chr17 | chr22 | Δ | KS p |")
        md.append("|---|---:|---:|---:|---:|")
        for ctx, e in cross.get("per_context", {}).items():
            chr17 = e.get("chr17_mean_c")
            chr22 = e.get("chr22_mean_c")
            delta = e.get("delta_mean")
            ksp = e.get("ks_p")
            def f(v, fmt="%.3f"):
                return fmt % v if isinstance(v, (int, float)) else "NA"
            md.append(f"| {ctx} | {f(chr17)} | {f(chr22)} | {f(delta)} | {f(ksp, '%.2e')} |")

        md.append("\n## Phase 2.4 — Gene-class stratification\n")
        md.append("```json")
        md.append(json.dumps(gene_class.get("groups", {}), indent=2))
        md.append("```")
        md.append("```json")
        md.append(json.dumps(gene_class.get("test_cd_vs_all_other", {}), indent=2))
        md.append("```")
        md.append("```json")
        md.append(json.dumps(gene_class.get("test_cd_vs_other_chr17", {}), indent=2))
        md.append("```")
        md.append(f"- cancer-driver genes used: {gene_class.get('cancer_driver_genes_used', 'NA')}")

        md.append("\n## Phase 2.5 — Splice fine profile (chr17 vs chr22)\n")
        md.append(f"- chr17 intron background mean c = {splice.get('intron_mean_c_background', 'NA')}")
        donor = splice.get("donor", {})
        if donor:
            mins = {k: v.get("mean_c") for k, v in donor.items() if v.get("mean_c") is not None}
            if mins:
                k_min = min(mins, key=mins.get)
                md.append(f"- chr17 donor minimum at offset {k_min} bp -> mean c = {mins[k_min]:.3f}")
        acc = splice.get("acceptor", {})
        if acc:
            mins_a = {k: v.get("mean_c") for k, v in acc.items() if v.get("mean_c") is not None}
            if mins_a:
                k_min = min(mins_a, key=mins_a.get)
                md.append(f"- chr17 acceptor minimum at offset {k_min} bp -> mean c = {mins_a[k_min]:.3f}")

        md.append("\n## Phase 2 verdict summary\n")
        # Build replication / framing verdict
        intron_replic = cross.get("replication_verdict", {}).get("qualitative_replicates")
        cd_test = gene_class.get("test_cd_vs_all_other", {})
        cd_d = cd_test.get("cohens_d_cd_minus_other")
        cd_p = cd_test.get("p_two_sided")
        md.append(f"- intron > exon (chr17): {cross.get('replication_verdict', {}).get('chr17_intron_gt_exon', 'NA')}")
        md.append(f"- intron > exon (chr22): {cross.get('replication_verdict', {}).get('chr22_intron_gt_exon', 'NA')}")
        md.append(f"- chr22 manuscript framing replicates on chr17: {intron_replic}")
        md.append(f"- cancer-driver vs other Cohen's d: {cd_d}, p={cd_p}")

        path = ru.GDTR_ROOT / "PHASE2_DECISION.md"
        path.write_text("\n".join(md))
        LOG.info("wrote %s", path)

        ru.write_done(PHASE, PHASE_OUT_DIR, {"path": str(path)}, step_name="writeup")


if __name__ == "__main__":
    main()
